- .idea/misc.xml
- backend/.run/Backend.run.xml
for speed up development (highly recommended to use IntelliJ)
> add backend Run Debug Configuration

- frontend_mobile/app/build.gradle.kts
- frontend_mobile/app/src/main/res/layout/activity_main.xml
- frontend_mobile/app/src/main/res/values/strings.xml
- frontend_mobile/gradle/libs.versions.toml
- frontend_mobile/gradle/wrapper/gradle-wrapper.properties
initial test, update AGP version
> update UI strings and dependencies for Android project

- backend/pom.xml
- backend/src/main/java/edu/cit/tooltrack/TooltrackApplication.java
- backend/src/main/java/edu/cit/tooltrack/controller/UserAuthController.java
- backend/src/main/java/edu/cit/tooltrack/controller/UserController.java
- backend/src/main/resources/application.properties
https://www.youtube.com/watch?v=hPr-Yc92qaY
> Added Swagger Docs and Modified Controller files to use Swagger

- backend/src/main/java/edu/cit/tooltrack/controller/UserAuthController.java
- backend/src/main/java/edu/cit/tooltrack/controller/UserController.java
- backend/src/main/java/edu/cit/tooltrack/dto/LoginRequest.java
- backend/src/main/java/edu/cit/tooltrack/dto/UserResponseDTO.java
- backend/src/main/java/edu/cit/tooltrack/entity/Notifications.java
- backend/src/main/java/edu/cit/tooltrack/entity/ToolCategory.java
- backend/src/main/java/edu/cit/tooltrack/entity/ToolItems.java
- backend/src/main/java/edu/cit/tooltrack/entity/ToolTransaction.java
- backend/src/main/java/edu/cit/tooltrack/entity/TransactionImage.java
- backend/src/main/java/edu/cit/tooltrack/entity/User.java
- backend/src/main/java/edu/cit/tooltrack/security/SecurityConfig.java
- backend/src/main/java/edu/cit/tooltrack/service/UserService.java
I modified the controller here, service, entities and the SWAGGER docs just for the 1st checkpoint
> modified the controller, swagger docs and service logic and added DTOs

- backend/api_test.sh
- backend/pom.xml
- backend/src/main/java/edu/cit/tooltrack/TooltrackApplication.java
- backend/src/main/java/edu/cit/tooltrack/Utils/S3DataExtractor.java
- backend/src/main/java/edu/cit/tooltrack/Utils/ToolItemDataExtractor.java
- backend/src/main/java/edu/cit/tooltrack/controller/DraftController.java
- backend/src/main/java/edu/cit/tooltrack/dto/S3DataDTO.java
- backend/src/main/java/edu/cit/tooltrack/dto/UploadToolItemDTO.java
- backend/src/main/java/edu/cit/tooltrack/repository/ToolCategoryRepository.java
- backend/src/main/java/edu/cit/tooltrack/repository/ToolItemRepository.java
- backend/src/main/java/edu/cit/tooltrack/security/SecurityConfig.java
- backend/src/main/java/edu/cit/tooltrack/service/S3Service.java
- backend/src/main/java/edu/cit/tooltrack/service/ToolItemService.java
- backend/src/main/java/edu/cit/tooltrack/service/UserService.java
i did not add the QR Dynamic yet only adding images to S3 and Extracting back the image.
For setting up the postman so it will display the base64 image please see my pinned comment *Environement Variables* for instructions
> Added: Controller for Adding toolItem, S3 Service and Draft Controller for testing toolItem endpoints.

- backend/pom.xml
- backend/src/main/java/edu/cit/tooltrack/controller/ToolItemController.java
- backend/src/main/java/edu/cit/tooltrack/controller/UserAuthController.java
- backend/src/main/java/edu/cit/tooltrack/dto/UploadToolItemDTO.java
- backend/src/main/java/edu/cit/tooltrack/dto/UserResponseDTO.java
- backend/src/main/java/edu/cit/tooltrack/entity/ToolItems.java
- backend/src/main/java/edu/cit/tooltrack/entity/User.java
- backend/src/main/java/edu/cit/tooltrack/security/OAuth2AuthenticationSuccessListener.java
- backend/src/main/java/edu/cit/tooltrack/security/SecurityConfig.java
- backend/src/main/java/edu/cit/tooltrack/security/jwt/CustomUserDetails.java
- backend/src/main/java/edu/cit/tooltrack/security/jwt/CustomUserDetailsService.java
- backend/src/main/java/edu/cit/tooltrack/security/jwt/JwtAuthenticationFilter.java
- backend/src/main/java/edu/cit/tooltrack/security/jwt/JwtService.java
- backend/src/main/java/edu/cit/tooltrack/service/S3Service.java
- backend/src/main/java/edu/cit/tooltrack/service/ToolItemService.java
- backend/src/main/java/edu/cit/tooltrack/service/UserService.java
- backend/src/main/java/edu/cit/tooltrack/utils/S3DataExtractor.java
- backend/src/main/java/edu/cit/tooltrack/utils/ToolItemDataExtractor.java
- backend/src/main/resources/application.properties
- frontend_web/src/App.jsx
- frontend_web/src/pages/OAuthSuccess.jsx
I did a lot of revision here, especially the JWT in this branch I included nalang the feature of controller na Tool Item
> Feature security

- .github/workflows/docker-image.yml
update changes in .yml (typo error)
> reupdate DOCKER CI CD

- frontend_mobile/README.md
detailed instructions on how to configure the project
> Add README.md with project overview, setup instructions, and development guidelines

- .github/workflows/docker-image.yml
added `--os-type Linux` in the `Deploy Backend Container` and `Deploy Frontend Container`
> feature_backend_config

- backend/src/main/java/edu/cit/tooltrack/controller/DraftController.java
- backend/src/main/java/edu/cit/tooltrack/controller/ToolItemController.java
- backend/src/main/java/edu/cit/tooltrack/dto/UploadToolItemDTO.java
- backend/src/main/java/edu/cit/tooltrack/entity/ReturnTransaction.java
- backend/src/main/java/edu/cit/tooltrack/entity/ToolImages.java
- backend/src/main/java/edu/cit/tooltrack/entity/ToolItems.java
- backend/src/main/java/edu/cit/tooltrack/entity/ToolTransaction.java
- backend/src/main/java/edu/cit/tooltrack/entity/TransactionImage.java
- backend/src/main/java/edu/cit/tooltrack/entity/User.java
- backend/src/main/java/edu/cit/tooltrack/repository/ReturnTransactionRepository.java
- backend/src/main/java/edu/cit/tooltrack/repository/ToolImagesRepository.java
- backend/src/main/java/edu/cit/tooltrack/repository/ToolItemRepository.java
- backend/src/main/java/edu/cit/tooltrack/repository/TransactionImageRepository.java
- backend/src/main/java/edu/cit/tooltrack/service/ImageChunkUploader.java
- backend/src/main/java/edu/cit/tooltrack/service/ReturnTransactionService.java
- backend/src/main/java/edu/cit/tooltrack/service/S3Service.java
- backend/src/main/java/edu/cit/tooltrack/service/ToolCategoryService.java
- backend/src/main/java/edu/cit/tooltrack/service/ToolImagesService.java
- backend/src/main/java/edu/cit/tooltrack/service/ToolItemService.java
- backend/src/main/java/edu/cit/tooltrack/service/TransactionImageService.java
- backend/src/main/resources/application.properties
- frontend_web/package-lock.json
- frontend_web/package.json
- frontend_web/src/pages/ChunkUploaderTest.jsx
> Feature_AddingToolItem

- backend/src/main/java/edu/cit/tooltrack/controller/DraftController.java
- backend/src/main/java/edu/cit/tooltrack/controller/UserAuthController.java
- backend/src/main/java/edu/cit/tooltrack/controller/UserController.java
- backend/src/main/java/edu/cit/tooltrack/security/SecurityConfig.java
- frontend_web/src/pages/LoginPage.jsx
- frontend_web/src/pages/Register.jsx
Frontend <-> Backend <-> Azure MySQL Server Flexible [db_tooltrack]
> Add test endpoint for database connection and update CORS settings

- backend/.gitignore
- backend/src/main/resources/application.properties
ive added hikari, optimizations (as average response time from SQL server to backend and vice versa is 500ms)
> update HikariCP configuration and add performance settings (accessing the SQL Server <-> Backend is slow as your response to flirt with wiman

- frontend_mobile/app/src/androidTest/java/edu/cit/tooltrack/LoginActivityTest.kt
- frontend_mobile/app/src/main/java/edu/cit/tooltrack/HomeScreenActivity.kt
- frontend_mobile/app/src/main/java/edu/cit/tooltrack/LoginActivity.kt
- frontend_mobile/app/src/main/java/edu/cit/tooltrack/MainActivity.kt
- frontend_mobile/app/src/main/java/edu/cit/tooltrack/ProfileScanActivity.kt
- frontend_mobile/app/src/main/java/edu/cit/tooltrack/QRScanActivity.kt
placeholder for transfer other IDE
> Add LoginActivity tests and improve UI components in MainActivity

- backend/src/main/java/edu/cit/tooltrack/controller/UserAuthController.java
- frontend_web/src/pages/LoginPage.jsx
> Modified: Made small revision in simple login

- backend/src/main/java/edu/cit/tooltrack/service/UserService.java
- frontend_web/src/pages/LoginPage.jsx
- frontend_web/src/pages/Register.jsx
> Enhance registration and login flows with error handling

- frontend_web/src/pages/LoginPage.jsx
I fix the login page due to unaccidentally merging outdated files
> Feature googlelogin

- frontend_mobile/app/src/main/AndroidManifest.xml
- frontend_mobile/app/src/main/java/edu/cit/tooltrack/api/BorrowedToolService.kt
- frontend_mobile/app/src/main/java/edu/cit/tooltrack/screens/home/HomeScreen.kt
- frontend_mobile/app/src/main/java/edu/cit/tooltrack/screens/home/HomeViewModel.kt
- frontend_mobile/app/src/main/java/edu/cit/tooltrack/screens/profile/BorrowedToolActivity.kt
- frontend_mobile/app/src/main/java/edu/cit/tooltrack/screens/profile/ProfileScreen.kt
This pull request introduces the Borrowed Tool feature, enabling users to manage borrowed tools within the application. Key updates include:
- A new Borrowed Tool screen with a list view and tool details navigation.
- Integration of `BorrowedToolService` API for fetching tool data.
- Enhancements to the home and profile screens to incorporate Borrowed Tool functionality.
- Expansion of the `CategorySection` component with collapsible grid and carousel views for improving user experience.
Please ensure the new feature implementations align with the existing application's design patterns and user flow. Suggestions or concerns during the review are highly welcomed
> Add Borrowed Tool feature with UI updates and API integration

- backend/src/main/java/edu/cit/tooltrack/controller/ToolItemController.java
- frontend_web/src/pages/ToolManagement.jsx
the dashboard in web tool management is online
> Feature web dashboard

- backend/src/main/java/edu/cit/tooltrack/controller/ToolItemController.java
> fixed the search endpoints to decode the url to fetch the correct word

- backend/src/main/java/edu/cit/tooltrack/controller/TransactionController.java
- backend/src/main/java/edu/cit/tooltrack/dto/TransactionsDTO.java
- backend/src/main/java/edu/cit/tooltrack/repository/ToolTransactionRepository.java
- backend/src/main/java/edu/cit/tooltrack/service/ToolTransactionService.java
- frontend_web/src/pages/Dashboard.jsx
[Intro: Justin Bieber]
Oh, woah
Oh, woah
Oh, woah
[Verse 1: Justin Bieber & Ludacris]
You know you love me (Yo), I know you care (Uh-huh)
Just shout whenever (Yo), and I'll be there (Uh-huh)
You are my love (Yo), you are my heart (Uh-huh)
And we will never, ever, ever be apart (Yo, uh-huh)
Are we an item? (Yo) Girl, quit playin' (Uh-huh)
We're just friends (Yo), what are you sayin'? (Uh-huh)
Said, "There's another" (Yo), and looked right in my eyes (Uh-huh)
My first love broke my heart for the first time, and I was like (Yo, uh-huh)
[Chorus: Justin Bieber]
Baby, baby, baby, oh
Like baby, baby, baby, no
Like baby, baby, baby, oh
I thought you'd always be mine, mine
Baby, baby, baby, oh
Like baby, baby, baby, no
Like baby, baby, baby, oh
I thought you'd always be mine, mine
You might also …
> Justin Bieber - Baby

- frontend_web/src/components/ToolDetailsModal.jsx
> feature_print_qr_niimbot

- backend/src/main/java/edu/cit/tooltrack/controller/UserAuthController.java
- backend/src/main/java/edu/cit/tooltrack/dto/LoginRequest.java
- backend/src/main/java/edu/cit/tooltrack/dto/UserResponseDTO.java
- backend/src/main/java/edu/cit/tooltrack/security/SecurityConfig.java
- backend/src/main/java/edu/cit/tooltrack/security/jwt/JwtService.java
- backend/src/main/java/edu/cit/tooltrack/service/ToolTransactionService.java
- backend/src/main/java/edu/cit/tooltrack/service/UserService.java
- frontend_web/src/components/AuthProvider.jsx
- frontend_web/src/pages/LoginPage.jsx
- frontend_web/src/pages/Register.jsx
I lahi the endpoint for admin and user here
user endpoints will be /auth/user/**
admin endoints will be /auth/admin/**
updated also the expiration time for JWT to 2hours
> Feature borrow
